### ISSUE TITLE
weights[j] = weights[j] + rate * (label - predicted) * x[j];

### ISSUE THREAD

**Issue by v71017** [tpeng/logistic-regression#2]
I am running the example and testing with one dataset

int[] x = { 1 ,0, 1, 1,1 };
The out for this is prob(1|x) = 0.022534261877410977.
Put actually in input file this data belongs  to category 1.
So why the probablity of this input for 1 is low.

**Comment by yangfengKAUST** [comment]
grad += (label - predicted) * x[j];
weight[j] += rate * grad

**Comment by v71017** [comment]
my doubt is , this data int[] x = { 1 ,0, 1, 1,1 }; is belonging to class "1" as per input file.
So the probability for 1 should be more ? why the result is 0.022534261877410977?
